# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: UBC Soaring
logo: /assets/site-images/soaring-icon.png
#email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  UBC Soaring unaffiliated student group at the University of British Colombia in Vancouver with a mission of promoting
  and supporting engineless flight in the campus community.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ubc-soaring.github.io" # TEMPORARY! the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: air
show_date: true

permalink: /:categories/:year/:month-:day-:title:output_ext

defaults:
  - scope:
      path: "*"
    values:
      layout: single
  - scope:
      path: "minutes/*"
    values:
      layout: single
      show_date: true
      read_time: true
      share: true
      related: true
      toc: true
      toc_label: "Table of Contents"
      toc_sticky: true
      sidebar:
        nav: resources
  - scope:
      path: "announcements/*"
    values:
      layout: single
      show_date: true
      read_time: true
      share: true
      related: true
      sidebar:
        - title: "Announcements"
          text: >-
            Stay up to date on the latest club news by keeping an eye on announcements posted here.
  - scope:
      path: "resources/*"
    values:
      layout: single
      show_date: true
      read_time: true
      share: true
      toc: true
      toc_label: "Table of Contents"
      toc_sticky: true
      sidebar:
        nav: resources

tag_archive:
  type: liquid
  path: /tags/

footer:
  links:
#    - label: "Twitter"
#      icon: "fab fa-fw fa-twitter-square"
#      url: "https://twitter.com/mmistakes"
#    - label: "GitHub"
#      icon: "fab fa-fw fa-github"
#      url: "https://github.com/mmistakes"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/ubcsoaring"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/company/ubcsoaring"
      
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

prose:
  # Prose is meant to be a simpler code-less editor; Hide a lot of the more technical files
  # I also included some stuff in the gitignore since I'm using a local version
  ignore: ['.github', '.jekyll-cache', '_site', '.gitignore', 'Gemfile', 'Gemfile.lock', 'README.md', '_sass', '_includes']
  media: "assets"
  
  # bugging out localprose
  siteurl: https://ubc-soaring.github.io
  
  metadata:
    "":
      - name: "title"
        field:
          element: "text"
          type: "text"
      - name: "layout"
        field:
          element: "select"
          label: "Layout"
          help: "Select the layout -- See https://mmistakes.github.io/minimal-mistakes/docs/layouts/ for options"
          alterable: true
          options:
            - name: Default
              value: single
            - name: Splash Page (Header image with text)
              value: splash
            - name: Super Wide Page (No ToC)
              value: wide
            - name: Home (Post Listing)
              value: home
            - name: Post Archive (see link)
              value: posts
            - name: Categories Archive (see link)
              value: categories
            - name: Tags Archive (see link)
              value: tags
            - name: Collection Archive (see link)
              value: collection
            - name: Category Archive (see link)
              value: category
            - name: Tag Archive (see link)
              value: tag
      - name: "excerpt"
        field:
          element: "textarea"
          label: "Excerpt Text"
          help: "Add a summary to the page. This is used on the splash layout, and included in post listings for posts."
    minutes/_posts:
      - name: "title"
        field:
          element: "text"
          type: "text"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Tags"
          help: "Add tags to this minutes post to help people find it"
          alterable: true
          options:
            - name: weekly-minutes
              value: weekly-minutes
            - name: general-meeting
              value: general-meeting
    announcements/_posts:
      - name: "title"
        field:
          element: "text"
          type: "text"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Tags"
          help: "Add tags to this announcement to help people find it"
          alterable: true
          options:
            - name: exec-team
              value: exec-team
            - name: recruitment
              value: recruitment
            - name: president
              value: president
            - name: treasurer
              value: treasurer
            - name: vp-marketing
              value: vp-marketing
            - name: vp-external
              value: vp-external
            - name: vp-internal
              value: vp-internal
            - name: secretary
              value: secretary
      - name: "toc"
        field:
          element: "checkbox"
          label: "Enable Table of Contents"
          value: false
      - name: "toc_label"
        field:
          element: "text"
          type: "text"
          label: "Label for the Table of Contents"
          value: "Table of Contents"
      - name: "toc_sticky"
        field:
          element: "checkbox"
          label: "Have the table of contents follow down the page as the user scrolls?"
          help: "Probably leave this set"
          value: true

